### ISSUE TITLE
Win/lose guarantee is broken.

### ISSUE THREAD

**Issue by hosza** [minhng/Decapawn#2]
The computer sometimes loses and sometimes wins. This must be either a bug or your statement about always winning is false. I attached two files: game and game2.

[game_lost.txt](https://github.com/minhng/Decapawn/files/3027082/game_lost.txt)
[game_win.txt](https://github.com/minhng/Decapawn/files/3027083/game_win.txt)

**Comment by hosza** [comment]
In fact I implemented 5x5 decapawn in C++ and found that if both player plays perfectly, then first player (White) wins. And second player (Black) can win only if White makes a mistake. The game tree that contains the proof of this is not to large: it contains 124514 nodes. I'm willing to send the data if you are interested.

**Comment by minhng** [comment]
@hosza Thanks for validating my statement. I checked and found that you were right! I will make changes to the statement and close the issue.
